### PR TITLE
Use nmcontrol's verifyFingerprint.

### PR DESCRIPTION
**Pull request by domob1812**
Instead of manually comparing a site's fingerprint to the blockchain,
use nmcontrol's verifyFingerprint method instead.  Also replace some
whitespace with tabs.

### CODE REVIEW

**Comment by JeremyRand** [comment]
I can confirm that https://dot-bit.bit still loads fine with this PR.  @domob1812 Can you provide a .bit domain that intentionally has an incorrect fingerprint so I can test that with this PR?

**Comment by domob1812** [comment]
Try https://tlsfail.bit/.

**Comment by phelixbtc** [comment]
I manually replaced the file in my firefox folder. Both https://dot-bit.bit and https://nameid.bit verify. https://tlsfail.bit fails as it should.

**Comment by JeremyRand** [comment]
Thanks for testing phelix.  I think that's good enough to merge.

**Pull request merged**
